---

- hosts: Server #IP Address for the hosts, EC2 instance running on amazon
  user: ubuntu
  sudo: yes

  tasks: 
  
    - name: Delete index.html file #task to delete the html file present 
      file: path=/var/www/html/index.html state=absent
 